### ISSUE TITLE
trl vllm-serve --model <model_name> got error

### ISSUE THREAD

**Issue by Tuziking** [huggingface/trl#3139]
I try to start the vLLM server with the desired model and the commend is `trl vllm-serve --model models/Qwen2.5-7B-Instruct`. The error is 
`[2025-03-23 11:11:16,072] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
INFO 03-23 11:12:20 __init__.py:190] Automatically detected platform cuda.
usage: trl
TRL CLI: error: argument command: invalid choice: 'vllm-serve' (choose from 'chat', 'dpo', 'env', 'grpo', 'kto', 'sft')`

**Comment by SydWingss** [comment]
I met the same problem, how did you solve that?

**Comment by qgallouedec** [comment]
```
pip install --upgrade trl
```

should solve the issue

**Comment by loong0918** [comment]
pip install --upgrade trl Didn't solve this problem. how did you solve that?
